version: "3.7"

services:
  react:
    image: node:21.4.0-bullseye-slim       # Usamos la versión de nodeJs 21.4.0
      # environment:
      # DB_HOST: $DB_HOST
    # DB_PORT: $DB_PORT
    ports:
      - 3000:3000
      - 80:3000
    command: bash -c "
      cd / &&
      npm install -C proyecto-daw-front/ next@latest -force &&
      npm --prefix proyecto-daw-front/ run dev"
    networks:
      - app-network
    volumes:
      - ./:/proyecto-daw-front    # esta carpeta probablemente necesita tener permisos de escritura por terceros

networks:
  app-network:
    external: true
    # driver: bridge
